---
version: '3'
services:
  
  prod_db:
    image: mysql:8.0     # https://hub.docker.com/_/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret_pwd
      MYSQL_DATABASE: my_db
    ports:
      - '3306:3306'
    #networks:
    #  - local-net
  
  assembly:
    build:
      dockerfile: assembly.Dockerfile
      context: ./
    volumes:
      - 'artifact:/tmp/App42PaaS-Java-MySQL-Sample/target/'
    depends_on:
      - prod_db
  
  prod_web:
    image: 'tomcat:jre8-alpine' #ENV CATALINA_HOME=/usr/local/tomcat
    hostname: 'tomcat'
    restart: always
    ports:
      - '8080:8080'
    volumes:
      - 'artifact:/usr/local/tomcat/webapps/'
      - '/etc/docker3/Config.properties:/etc/Config.properties'
    depends_on:
      - prod_db
    #networks:
    #  - local-net
  
volumes:
  artifact:
